### ISSUE TITLE
fail login HID devices

### ISSUE THREAD

**Issue by dragoneye3055** [hak5/usbrubberducky-payloads#128]

**Comment by dragoneye3055** [comment]
`$ ./android-pin-bruteforce crack -l 5
Android PIN brute-force :: version 0.2
[INFO] Loading optimised PIN list for 5 digits (optimised-pin-length-5.txt)
[INFO] PIN list contains 100000 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found`

**Comment by hak5darren** [comment]
It sounds like you may be looking for a different repository. Perhaps https://github.com/urbanadventurer/Android-PIN-Bruteforce ?

**Comment by dragoneye3055** [comment]
unlocked samsung a10e phone ?

**Comment by hak5darren** [comment]
Wrong repo mate.
