### ISSUE TITLE
Long-lived token deprecated

### ISSUE THREAD

**Issue by haglefar** [hak5/usbrubberducky-payloads#147]
Dropbox has retired the long-lived token and replaced them with refresh-token/short-lived tokens.
Because of how the POST-call is formulated we now need to reprogram the ducky each time we use it (it is still possible to generate access-tokens, but they are only valid for 4 hours).

**Comment by 0iphor13** [comment]
Payloads are community made, so you are better of to contact the payload dev or to update the payload yourself :)
This is not an issue with the ducky itself.

**Comment by haglefar** [comment]
Thank you, i see that now. 
Ill post directly to the dev : )
