### ISSUE TITLE
Only saves one password

### ISSUE THREAD

**Issue by Smurfboi007** [hak5/usbrubberducky-payloads#151]
Tried it and everything works fine, it's just that the file on dropbox only contains one password that seems to have overwritten all other passwords since only one password is showing for of all the websites. (Even though I check in chrome and the passwords are different)

Anyways thanks for creating this script!

**Comment by Smurfboi007** [comment]
Here is the ps1 I'm using (Couldn't upload it as ps1): 
[Browser-Passwords-Dropbox-Exfiltration.txt](https://github.com/hak5/usbrubberducky-payloads/files/9739513/Browser-Passwords-Dropbox-Exfiltration.txt)

**Comment by dallaswinger** [comment]
please link the payload you're referencing **directly in this repository**
