### ISSUE TITLE
powershell error

### ISSUE THREAD

**Issue by Leanshreds** [hak5/usbrubberducky-payloads#154]
hey, I'm confused with this one because when i copy paste the code into shell it goes smoothly but when its excuting on the rubber ducky i get the syntax error mark in powershell. I cant figure out why..[
![Screenshot_12](https://user-images.githubusercontent.com/53378203/194694667-b4d2ffce-8a51-4ce4-a3c9-7d9fe9b4a777.png)

**Comment by Leanshreds** [comment]
oh i see.. the "" are turning to @@ .. im using https://ducktoolkit.com/encode to compile my payload.

**Comment by Leanshreds** [comment]
I solved this by changing the language to" United States"
![index](https://user-images.githubusercontent.com/53378203/194695726-549489e5-af9c-4779-a72d-9f25e9c82586.png)

**Comment by dallaswinger** [comment]
> oh i see.. the "" are turning to @@ .. im using https://ducktoolkit.com/encode to compile my payload.

https://payloadstudio.hak5.org
is the only supported encoder/compiler for the USB Rubber Ducky and DuckyScript 1.0,3.0
