### ISSUE TITLE
ALT J

### ISSUE THREAD

**Issue by alstergee** [hak5/usbrubberducky-payloads#191]
i find ALT J does nothing in a windows environment was this meant to be a LEFTARROW ENTER thing?

**Comment by alstergee** [comment]
payload studio community edish

**Comment by alstergee** [comment]
ah i see this somehow got posted to the root i was in a specific payload for disabling windows defender my apologies

**Comment by alstergee** [comment]
in the code they laid out they appear to be using the windows s to search then searching windows security in a string then pressing enter to open it but then they use ALT j where i would assume they meant to apply a LEFTARROW ENTER move to bypass windows UAC

**Comment by alstergee** [comment]
Apologies.

https://hak5.org/blogs/payloads/disabling-defender-on-win-22h2-maschines

**Comment by dallaswinger** [comment]
@alstergee top of the payload clearly states: Tested on German Computers

ALT j is the shortcut for accept in German. Change it to ALT y for english.

**Comment by alstergee** [comment]
Well I feel dumb thanks for pointing that out.
