### ISSUE TITLE
Problem with French MacOS layout :(

### ISSUE THREAD

**Issue by blabut** [hak5/usbrubberducky-payloads#202]
Hi, I just got my RubberDucky and am super disappointed not be able to use it properly because of keyboard layouts issues. Is the layout for the French mac keyboard available anywhere ? I tried tinkering around blindly with `fr.json` in order to make it fit to most common special chars but it's far for perfect. Furthermore, the file upload functionality does not seem to work on the community editor (it has no effect in my case). Any help / hack would be appreciated... Thanks a lot !
I would be glad to contribute by crafting a clean `fr_mac.json`, but to do so I would need:
- some resource in order to figure out how to determine the third byte from each key element in the json structure
- the bug in the payload editor to be fixed in order to be able to actually import `json` files
Thank you very much !

**Comment by blabut** [comment]
@hak5dev @hak5darren any help on this ? Would love try out this new bad ducky... Thanks !

**Comment by dallaswinger** [comment]
> @hak5dev @hak5darren any help on this ? Would love try out this new bad ducky... Thanks !

Sorry for the delayed response - I'm working on pushing a hotfix for PayloadStudio for local language file upload. In the meantime import via URL should be working as an alternative workaround; regardless, expect a 1.2.2 to be out as soon as I have the fixes tested here soon.

As for finding out the bytes for specific keys something like https://manytricks.com/keycodes/ could potentially be of use though I have no personal experience with it. Alternatively you can identify which /dev/hidraw your keyboard is attached to and read the values using xxd or similar.

**Comment by dallaswinger** [comment]
PayloadStudio 1.2.2 is live and should address the issues with language files.

**Comment by blabut** [comment]
Hey,Thank you so much for your reactivity ! Will definitely try this out over the weekend :) Le 6 janv. 2023 à 21:01, Dallas Winger ***@***.***> a écrit :﻿
PayloadStudio 1.2.2 is live and should address the issues with language files.

**Comment by Pixayl** [comment]
Hi, just tested version 1.2.2 of Payload Studio, the issue seems to be still here, I have the problem with at least "=" and "-" characters.

Thanks for the work !

**Comment by dallaswinger** [comment]
> Hi, just tested version 1.2.2 of Payload Studio, the issue seems to be still here, I have the problem with at least "=" and "-" characters.
> 
> Thanks for the work !

the language files were not changed, the bug that was fixed was choosing a language file had no affect.

**Comment by Pixayl** [comment]
My bad, I misunderstood the ticket.

While I'm here, I want to thank again Darren and you for the work you've done, I'm currently reading the textbook, I'm very impressed.

**Comment by dallaswinger** [comment]
I'm gonna go ahead and close this issue as the _bug_ (in PayloadStudio) was solved to the best of my knowledge. If you wish to post a new issue pertaining to _just_ the language file problems - feel free.
