### ISSUE TITLE
Missing Command

### ISSUE THREAD

**Issue by Halldog** [hak5/usbrubberducky-payloads#226]
It needs a command ENTER after string 83.

**Comment by dallaswinger** [comment]
absolutely 0 context.

Need to reference a payload.

**Comment by Halldog** [comment]
https://github.com/hak5/usbrubberducky-payloads/blob/master/payloads/library/exfiltration/DUCKY-WIFI_GRABER/

**Comment by dallaswinger** [comment]
Payload updated. Thank you for the report
