### ISSUE TITLE
OS_DETECT

### ISSUE THREAD

**Issue by 600d1nt3nt10ns** [hak5/usbrubberducky-payloads#275]
OS_DETECT makes false determination and shows MACOS (12.6.3) as LINUX.

**Comment by dallaswinger** [comment]
already open: https://github.com/hak5/usbrubberducky-payloads/issues/179
please share what mode youre using the extension in. (basic vs advanced)

**Comment by 600d1nt3nt10ns** [comment]
Hello

I tested both modes and they both failed. MACOS was categorised as LINUX.

BR

G.



Kontakt Dallas Winger ***@***.***>) kirjutas kuupäeval R,
24. märts 2023 kell 10:09:
