### ISSUE TITLE
Issue with Dropbox "missing scope"

### ISSUE THREAD

**Issue by ea3iav** [hak5/usbrubberducky-payloads#286]
Invoke-RestMethod : {"error_summary": "missing_scope/.", "error": {".tag": "missing_scope", "required_scope":
"files.content.write"}}
En línea: 1 Carácter: 13
+ $response = Invoke-RestMethod -Uri https://content.dropboxapi.com/2/f ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by dallaswinger** [comment]
you need to link what payload you're trying and what you have done to if at all to configure said payload - at a minimum

**Comment by ea3iav** [comment]
Sorry! I thought that it could be a general issue, as all Payloads that require a file to be send to dropbox would have the same problem. 
I am having issues with the Wifigrabber 
thank you!

**Comment by dallaswinger** [comment]
> Sorry! I thought that it could be a general issue, as all Payloads that require a file to be send to dropbox would have the same problem. I am having issues with the Wifigrabber thank you!

please link the payload

**Comment by dallaswinger** [comment]
please resubmit issue using the new issue template to ensure enough details are provided that someone can assist you.

**Comment by ea3iav** [comment]
Really easy 
Not trying again
