### ISSUE TITLE
cmd error when inoutting curl command from setup dropbox

### ISSUE THREAD

**Issue by G4k3r** [hak5/usbrubberducky-payloads#290]
is this the proper format curl https://api.dropbox.com/oauth2/token -d code=ilileTdCNFw8AAAAAAAAAFZweC4ck6XN_KBdSolmnbhg -d grant_type=authorization_code   -u 5u3fuf5ux5c67ut:f2m3kxkfa9s866u everytime i input this into power shell or even cmd prompt i get an error :curl: (35) Recv failure: Connection reset by peer

or 

 Parameter cannot be processed because the parameter name 'u' is ambiguous. Possible matches include:
-UseBasicParsing -Uri -UseDefaultCredentials -UserAgent.
At line:1 char:129

**Comment by dallaswinger** [comment]
Not a payload issue.

**Comment by dallaswinger** [comment]
Issues are for problems with specific payloads. This isn't a repo for dropbox API assistance. You also shared your credentials - at a minimum youll now need to revoke those keys.

**Comment by G4k3r** [comment]
i didnt share the real credentials those are dummy credentials. OKAY my point is following the instructions on the payload and i cant get a successful outcome it is an issue. you know what's missing or?

**Comment by dallaswinger** [comment]
you shared 0 information regarding what payload you're trying. I suggest using [the issue form](https://github.com/hak5/usbrubberducky-payloads/issues/new?assignees=&labels=&template=payload_bug.yaml&title=%5BPayload+BUG%5D+write+a+short+description+here) to guide you in creating a valid and actionable bug report.
