### ISSUE TITLE
README.md shields.io invalid

### ISSUE THREAD

**Issue by MocconaCoffee** [hak5/usbrubberducky-payloads#296]
The shields.io badges for the YouTube badges are both outputting an invalid tag, I'm assuming it's related to the YouTube handle change that was done recently. 

I've made my own attempts to resolve the issue by viewing the page source for the Hak5 channel to confirm the channel id is correct, thus far I haven't been able to fix/find a fix for it. 

Just making this aware for when a solution is made public.

See image below;

![image](https://user-images.githubusercontent.com/66985140/230839204-7bfe55e8-9d6b-4d3f-b146-ec2f4c52e487.png)

**Comment by dallaswinger** [comment]
They are valid. 
![image](https://user-images.githubusercontent.com/9642419/230964030-f22e192f-4e24-468a-a87e-0a26d8437285.png)


this happens nightly almost. I assume due to too many views daily getting the API throttled.
