### ISSUE TITLE
after showing the image  the F11 key could be pressed to make the page full screen to bring more impact

### ISSUE THREAD

**Issue by yadhumanikandan** [hak5/usbrubberducky-payloads#310]
https://github.com/hak5/usbrubberducky-payloads/blob/af96f7d8e158cdc7b7d110f36edb2b013e8415e5/payloads/library/prank/-RD-JumpScare-2.0/JumpScare2.0.txt#L17

**Comment by dallaswinger** [comment]
You're welcome to PR suggestions to payloads. This is not an issue.
