### ISSUE TITLE
[Change the password of the windows user] LEFT_ARROW doesnt work

### ISSUE THREAD

**Issue by Anonym1453** [hak5/usbrubberducky-payloads#352]
when I plug my raspberry pi pico into my pc, the left button is not pressed and instead of "yes" It clicks "no".

(I'm new to ducky script)

**Comment by dallaswinger** [comment]
This repo is only for the USB Rubber Ducky.

`when I plug my raspberry pi pico into my pc,` implies you're using a clone.
