### ISSUE TITLE
I search for a coding programm

### ISSUE THREAD

**Issue by Thesek2008** [hak5/usbrubberducky-payloads#364]
hi i search for a coding programm that i can in stall on my pc with automatic things what it shows me that i can tab to set it in you know what i mean in german it means autoverfolständigung i wanted to ask if there is any programm/tool what i can download what can do that

**Comment by 0iphor13** [comment]
Alter, wo ist das bitte ein "issue" wert... 

Can be closed.

**Comment by Thesek2008** [comment]
no i want to get an answer

**Comment by Thesek2008** [comment]
ich will ein programm haben das mir des zeug autoverfolständigt auch ofline darum gehts mir

**Comment by Thesek2008** [comment]
> Alter, wo ist das bitte ein "issue" wert...
> 
> Can be closed.

verstehst du
