### ISSUE TITLE
Small typos in Copy-And-Waste

### ISSUE THREAD

**Issue by Computeroid** [hak5/usbrubberducky-payloads#368]
Hey, just wanted to let you know that there is a small typo at the [Copy-And-Waste](https://github.com/hak5/usbrubberducky-payloads/blob/master/payloads/library/exfiltration/Copy-And-Waste/payload.txt) payload.txt file.

### **Typos:**
1. Line 10 there is a missing 'r' after GUI
2. Line 11 there is a missing delay setting after 'DELAY' I personally set it to 500 and that seemed to work just fine.

That's it thank you for reading

**Comment by dallaswinger** [comment]
@I-Am-Jakoby @atomiczsec

**Comment by dallaswinger** [comment]
@atomiczsec please fix

**Comment by dallaswinger** [comment]
Someone else PR'd the fixes for this. @atomiczsec
