### ISSUE TITLE
[Payload BUG] write a short description here

### ISSUE THREAD

**Issue by ZekePolarisBSH** [hak5/usbrubberducky-payloads#377]
### Payload Title

Multiple Path Error?

### Payload URL

https://github.com/hak5/usbrubberducky-payloads/tree/master/payloads/library/prank/Alien%20Message%20From%20Computer

### Payload Setup

It requires no set up it says.

### Problem Description

New-Item : Cannot bind parameter because parameter 'Path' is specified more than once. To provide multiple values to
parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At line:1 char:65
+ ...  -Path ".\script.py" -ItemType "file" -ForceSet-Content -Path ".\scri ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindingException
    + FullyQualifiedErrorId : ParameterAlreadyBound,Microsoft.PowerShell.Commands.NewItemCommand

### Troubleshooting steps

Not sure if I really need to edit this or is there a bug going on. In other words I don't know what steps to take for this.

### Suspected Cause

Possible Bug or it really needs to be edited by the user. Idk...

### Screenshots or additional information

I don't know what it means by I am using PayloadStudio to encode this payload since it said nothing need to be done to use it and isn't it already encoded? Also can't even use PayloadStudios. Also the files I got from this was downloaded from a source that already made these files ready for us on the Flipper. Any ideas anyone? Also I noticed a lot of the safe files for these things are starting to get detected even with AV turned off fully. Think something wrong with my system?

### Checklist ✅ - READ CAREFULLY

- [X] I checked and didn't find a similar issue already reported
- [X] I am using PayloadStudio to encode this payload
- [X] I made sure to redact any private information in the details shared above
- [X] I have read and followed the documentation provided by the original payload author and configured the payload (if required)
- [X] I have confirmed I am deploying this payload with the correct device intended by the original author (Original USB Rubber Ducky vs New USB Rubber Ducky)
- [X] I have confirmed I am deploying this payload on the correct target host intended by the original author (Windows, Mac, Linux, etc)
- [X] I have confirmed the payload is compiled in the correct keyboard language for the target host I'm trying to deploy it on (US, DE, etc)
- [ ] I have actually read the above checkboxes before checking them, including this one, which I have intentionally left unchecked as confirmation of this statement

### Agreement

- [X] I believe this is an issue with the actual payload itself. I acknowledge this form is not a request for help following instructions.
- [X] I have carefully read and filled out every section of this issue form to the best of my ability. I acknowledge by providing insufficient information I cannot receieve adequate assistance.

**Comment by aleff-github** [comment]
Hi, thanks for reporting this bug.
The problem consists in the fact that the line of code number 27 does not terminate the command and, therefore, it rejoins the next line, i.e. 30 by continuing to write and not separating the two commands.

In order to fix this bug there can be many solutions, one of which has been considered in the following Pull Request https://github.com/hak5/usbrubberducky-payloads/pull/378

Thank you for reporting this problem and I encourage you to report others if you find any in the future.

**Comment by ZekePolarisBSH** [comment]
No problem and I do my best, without flood/spam by accident due to I like to type. Also keep up the good work

**Comment by dallaswinger** [comment]
fix pr merged
