### ISSUE TITLE
RDuck

### ISSUE THREAD

**Issue by scansudo** [hak5/usbrubberducky-payloads#381]

**Comment by 0iphor13** [comment]
What a waste of time.

**Comment by scansudo** [comment]
I apologize I'm barely learning my way around GitHub . Don’t get me wrong I'm a coder I just never used GitHub like that but now I'm starting too

**Comment by 0iphor13** [comment]
Even if you are completely new to the internet, I would assume that you actually put some sort of text or explaination in your issue. Neither Title nor the missing text will do anything...

So you either update it and explain your issue or you can close it, as it is worth nothing.

**Comment by scansudo** [comment]
Understood. Before I do may I ask, are you willing to be my mentor ? I could use some tips every now and then

**Comment by 0iphor13** [comment]
I have no idea in what sort of topic to begin with, but I also don't have time being your mentor.

Just make your issue here useful please or close it. Telling you that is my community service here lol.
