### ISSUE TITLE
[Ducky BUG/Feature(?)] Is there a way use the iPadOS "globe" key?

### ISSUE THREAD

**Issue by bessx** [hak5/usbrubberducky-payloads#384]
Looking to run a script on iPadOS or iOS, and I was trying to emulate the "globe" (🌐) key.  Since there's a usb/bluetooth keyboard for the iPad with a global key, it should be possible to emulate, right?  

Is there some shortcut for this, or is this not implemented? Please let me know best practices for this.

Thanks.

**Comment by dallaswinger** [comment]
Issues on this repo are dedicated to _bugs in payloads_ 

You will have better luck asking for help on discord or the forums.
