### ISSUE TITLE
[Payload BUG] write a short description here

### ISSUE THREAD

**Issue by rileymilo** [hak5/usbrubberducky-payloads#387]
### Payload Title

can you separate the Discord_Windows_Wifi_IP-Info script into sections?

### Payload URL

https://github.com/hak5/usbrubberducky-payloads/blob/master/payloads/library/exfiltration/Discord_Windows_Wifi_IP-Info/payload.txt

### Payload Setup

NIL

### Problem Description

Can you separate the script into sections? for example i only want to use the script to get the IP address and want to make the script shorter to make the payload quicker.

### Troubleshooting steps

I have already tried it myself but am not succeeding .

### Checklist ✅ - READ CAREFULLY

- [X] I checked and didn't find a similar issue already reported
- [X] I am using PayloadStudio to encode this payload
- [X] I made sure to redact any private information in the details shared above
- [X] I have read and followed the documentation provided by the original payload author and configured the payload (if required)
- [X] I have confirmed I am deploying this payload with the correct device intended by the original author (Original USB Rubber Ducky vs New USB Rubber Ducky)
- [X] I have confirmed I am deploying this payload on the correct target host intended by the original author (Windows, Mac, Linux, etc)
- [X] I have confirmed the payload is compiled in the correct keyboard language for the target host I'm trying to deploy it on (US, DE, etc)
- [X] I have actually read the above checkboxes before checking them, including this one, which I have intentionally left unchecked as confirmation of this statement

### Agreement

- [X] I believe this is an issue with the actual payload itself. I acknowledge this form is not a request for help following instructions.
- [X] I have carefully read and filled out every section of this issue form to the best of my ability. I acknowledge by providing insufficient information I cannot receieve adequate assistance.

**Comment by dallaswinger** [comment]
Issue title left default

you checked the box that said not to check it - confirming you didnt read. 

this is not an issue this is a request for help. Try asking in discord or similar but a github issue is not the appropriate avenue.
