### ISSUE TITLE
payload/Hardware

### ISSUE THREAD

**Issue by anonymous2007100** [hak5/usbrubberducky-payloads#405]
Whenever i try to load any payload it runs one that was used before but now is long deleted and i cant run any other ones cuz it just keeps running the old one that is not present wich makes no sense and i need help to fix this because it makes my usb unusable

**Comment by dallaswinger** [comment]
Issues on this repo are related to specific payload functionality. You're welcome to join discord and ask for assistance https://discord.gg/hak5 or open an official support ticket https:// hak5.org/support

the TLDR though is, the only way the ducky will do anything beyond its default is if the `inject.bin` says to - so it sounds like the file is either not getting replaced properly or its not getting replaced with what you think.
