### ISSUE TITLE
Error line 14 

### ISSUE THREAD

**Issue by BourbonGod** [hak5/usbrubberducky-payloads#430]
I am running the script on my flipper zero and i keep getting an error for line 14. It says no keycode defined.

**Comment by 0iphor13** [comment]
Lol, I wonder why... maybe because of non licensed duckyscript

**Comment by BourbonGod** [comment]
So no help then?

**Comment by 0iphor13** [comment]
I'd say so.

- issue without any context
- on a 3rd party device with non licensed duckyscript 

You are better ask in some flipper community

**Comment by BourbonGod** [comment]
Id figured id ask here cuz im pretty sure its an issue with the script itself the other payloads ive ran have worked

**Comment by 0iphor13** [comment]
And still you haven't provided any info except you using a 3rd party device... which makes debugging the issue probably obsolete anyways.

**Comment by BourbonGod** [comment]
Well i connect the flipper to my phone and run the script it runs for a second the says there is an error with line 14 undefined key but when i look at the script line 14 is blank

**Comment by dallaswinger** [comment]
as noted in the README of this repo: 

> Payloads here are written in official DuckyScript™ specifically for the USB Rubber Ducky.

**Comment by Kirankali149** [comment]
USB Rubber Ducky Script
