### ISSUE TITLE
i have problem for change user password rep on prank section

### ISSUE THREAD

**Issue by ErvinGh88** [hak5/usbrubberducky-payloads#439]
I dont know where (in the script) I have to set my new password, too when it changed I knew the new one

**Comment by cribb-it** [comment]
Got a link to the files?

**Comment by cribb-it** [comment]
if it this [Change_the_password_of_the_windows_user](https://github.com/hak5/usbrubberducky-payloads/blob/bf2dfb7c17d0661624bb418c9576cc9fc51f8832/payloads/library/execution/Change_the_password_of_the_windows_user/payload.txt#L15) the you change `example` to what you want the new password to be

**Comment by ErvinGh88** [comment]
Thanks!!!
