### ISSUE TITLE
problem with "Funni_Stick_V3"

### ISSUE THREAD

**Issue by blackeyes1200** [hak5/usbrubberducky-payloads#57]
Problem with the exclusion path with the argument $duckletter. I tried differents things but didn't manage to find a solution.

**Comment by dallaswinger** [comment]
@MakeshiftMaker

**Comment by MakeshiftMaker** [comment]
Are you using twin-duck firmware on your Ducky? What error does it throw you exactly and what did you try to fix it? @blackeyes1200

**Comment by gaskann16** [comment]
@dallaswinger I am getting the same exact error about the $duckletter issue. I am also using it on my flipper, which claims to have been figured out from what I have read.

**Comment by dallaswinger** [comment]
> @dallaswinger I am getting the same exact error about the $duckletter issue. I am also using it on my flipper, which claims to have been figured out from what I have read. ![318970438_662583092199040_3930648229223125057_n](https://user-images.githubusercontent.com/120290349/207219153-6ebb807f-5ac8-488f-a576-cacad4167d61.jpg)

Firstly, I did not author this payload. Secondly, a payload that was authored for the Original Rubber Ducky running a different firmware (twin duck, as noted directly by the author) almost certainly is not going to be plug and play compatible with a Flipper...

**Comment by MakeshiftMaker** [comment]
> @dallaswinger I am getting the same exact error about the $duckletter issue. I am also using it on my flipper, which claims to have been figured out from what I have read. ![318970438_662583092199040_3930648229223125057_n](https://user-images.githubusercontent.com/120290349/207219153-6ebb807f-5ac8-488f-a576-cacad4167d61.jpg)

as stated above this script was made for the original ducky running the twin duck firmware, it requires the ducky to be a mass storage device at the same time so it can find and execute the mimikatz exe saved ON the ducky itself. This does not work with the flipper zero as it is not a mass storage device (I looked into it tho its not possible yet sadly). But you can use the Simple_User_Password_Grabber by foxtrot (not from makozort im an idiot). This script does not require a mass storage device and just loads the mimikatz executable from an online source.

**Comment by gaskann16** [comment]
Yea I have successfully used that one. I have a bounty set out for a local college and I am wanting to go in with some additional tools. If I am caught in any way, I fail it.

**Comment by gaskann16** [comment]
> > @dallaswinger I am getting the same exact error about the $duckletter issue. I am also using it on my flipper, which claims to have been figured out from what I have read. ![318970438_662583092199040_3930648229223125057_n](https://user-images.githubusercontent.com/120290349/207219153-6ebb807f-5ac8-488f-a576-cacad4167d61.jpg)
> 
> as stated above this script was made for the original ducky running the twin duck firmware, it requires the ducky to be a mass storage device at the same time so it can find and execute the mimikatz exe saved ON the ducky itself. This does not work with the flipper zero as it is not a mass storage device (I looked into it tho its not possible yet sadly). But you can use the Simple_User_Password_Grabber. This script does not require a mass storage device and just loads the mimikatz executable from an online source. (online source not included)

- Yea i gathered that much from reading through it after the fact. I swear where i grabbed it from it was being advertised as patched and working for the flipper. Ill have to read through it again and see if i missed something.
